# Generated by Django 5.2.17 on 2026-08-15 14:00

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('extracting', 'Unpacking archives'), ('parsing', 'Reading source files'), ('ready', 'Ready for review'), ('failed', 'Failed')], default='uploaded', max_length=20)),
                ('step', models.CharField(choices=[('upload', 'Upload'), ('review', 'Review sources'), ('costs', 'Cost rates'), ('assumptions', 'Assumptions'), ('result', 'Build')], default='upload', max_length=20)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('progress_message', models.CharField(blank=True, max_length=255)),
                ('error', models.TextField(blank=True)),
                ('parse', models.JSONField(blank=True, null=True)),
                ('choices', models.JSONField(blank=True, default=dict)),
                ('output_name', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
